export const skillAliases = {
    "React": ["React", "React.js"],
    "Node.js": ["Node", "Node.js"],
    "Express": ["Express", "Express.js"],
    "Vue": ["Vue", "Vue.js"],
    "DBMS": ["DBMS", "Database Management System"],
    "OOPS": ["OOPS", "Object Oriented Programming", "Object-Oriented Programming"],
    "AWS": ["AWS", "Amazon Web Services"],
    "Artificial Intelligence": ["Artificial Intelligence", "AI"],
    "Natural Language Processing": ["Natural Language Processing", "NLP"],
    "REST API": ["REST API", "RESTful API"]
};
export const skillsDatabase = [
    // Programming Languages
    "C",
    "C++",
    "C#",
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "Go",
    "Rust",
    "Kotlin",
    "Swift",
    "PHP",
    "Ruby",
    "R",
    "Scala",
    "Perl",
    "MATLAB",
    "Dart",
    "SQL",
    // Frontend
    "HTML",
    "CSS",
    "SASS",
    "Bootstrap",
    "Tailwind CSS",
    "Material UI",
    "Chakra UI",
    "React",
    "Next.js",
    "Vue",
    "Nuxt.js",
    "Angular",
    "Svelte",
    "Redux",
    // Backend
    "Node.js",
    "Express",
    "Spring Boot",
    "Django",
    "Flask",
    "FastAPI",
    "Laravel",
    "ASP.NET",
    "NestJS",
    // Databases
    "MySQL",
    "PostgreSQL",
    "MongoDB",
    "Firebase",
    "Oracle",
    "SQLite",
    "Redis",
    "MariaDB",
    "Cassandra",
    "DynamoDB",
    // Cloud
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Jenkins",
    "CI/CD",
    "Netlify",
    "Vercel",
    "Heroku",
    // Version Control
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    // AI / ML
    "Machine Learning",
    "Deep Learning",
    "Artificial Intelligence",
    "Generative AI",
    "Prompt Engineering",
    "LLM",
    "TensorFlow",
    "PyTorch",
    "Scikit-learn",
    "Keras",
    "LangChain",
    "OpenCV",
    "Natural Language Processing",
    "Computer Vision",
    // Data Science
    "NumPy",
    "Pandas",
    "Matplotlib",
    "Seaborn",
    "Power BI",
    "Tableau",
    // Mobile
    "Android",
    "Flutter",
    "React Native",
    // Testing
    "JUnit",
    "Jest",
    "Mocha",
    "Cypress",
    "Selenium",
    "Postman",
    "Swagger",
    // Operating Systems
    "Linux",
    "Windows",
    "Unix",
    // Core CS
    "Data Structures",
    "Algorithms",
    "DBMS",
    "OOPS",
    "Operating Systems",
    "Computer Networks",
    "Software Engineering",
    "Cloud Computing",
    "Compiler Design",
    "Computer Architecture",
    // Security
    "Cyber Security",
    "JWT",
    "OAuth",
    // APIs
    "REST API",
    "GraphQL",
    "Axios",
    "JSON",
    "XML",
    // Tools
    "VS Code",
    "Visual Studio",
    "IntelliJ IDEA",
    "PyCharm",
    "Eclipse",
    "Figma",
    "Canva",
    "Jupyter Notebook",
    // Soft Skills
    "Leadership",
    "Teamwork",
    "Problem Solving",
    "Communication",
    "Critical Thinking",
    "Time Management",
    "Adaptability",
    // Software Concepts
    "Agile",
    "Scrum",
    "Microservices",
    "MVC",
    "Design Patterns"
];